name: ntl build
on: [pull_request, push, workflow_dispatch]

jobs:
  ci:
    name: Build
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: ucrt64,  env: ucrt-x86_64 }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          install: mingw-w64-${{ matrix.env }}-toolchain
          update: true

      - name: Build ntl
        shell: msys2 {0}
        run: |
          MINGW_ARCH=${{ matrix.sys }} makepkg-mingw --noconfirm --syncdeps
          pacman --upgrade --noconfirm mingw-w64-*

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ntl_${{ matrix.env }}
          path: |
            mingw-w64-*.pkg.tar.*
